// Fix: Added constants for trading pairs and strategies.
export const TRADING_PAIRS = [
    "BTC/USDT",
    "ETH/USDT",
    "BNB/USDT",
    "SOL/USDT",
    "XRP/USDT",
    "DOGE/USDT",
    "ADA/USDT",
    "SHIB/USDT",
    "AVAX/USDT",
    "TRX/USDT",
    "DOT/USDT",
    "LINK/USDT",
    "MATIC/USDT",
    "BCH/USDT",
    "ICP/USDT",
    "LTC/USDT",
    "NEAR/USDT",
    "UNI/USDT",
    "LEO/USDT",
    "ETC/USDT",
    "ATOM/USDT",
    "INJ/USDT",
    "OP/USDT",
    "XLM/USDT",
    "OKB/USDT",
    "FIL/USDT",
    "IMX/USDT",
    "HBAR/USDT",
    "CRO/USDT",
    "VET/USDT",
    "APT/USDT",
    "MKR/USDT",
    "ARB/USDT",
    "GRT/USDT",
    "STX/USDT",
    "RNDR/USDT",
    "ALGO/USDT",
    "EGLD/USDT",
    "AAVE/USDT",
    "SAND/USDT",
    "MANA/USDT",
    "AXS/USDT",
    "THETA/USDT",
    "XTZ/USDT",
    "FTM/USDT",
    "EOS/USDT",
    "SNX/USDT",
    "APE/USDT",
    "CAKE/USDT",
    "FLOW/USDT",
    "KCS/USDT",
    "CHZ/USDT",
    "QNT/USDT",
    "GALA/USDT",
    "CRV/USDT",
    "LDO/USDT",
    "NEO/USDT",
    "WAVES/USDT",
    "ZIL/USDT",
    "KAVA/USDT",
    "DYDX/USDT",
    "COMP/USDT"
];

export const SUPPORTED_EXCHANGES = [
    { id: 'binance', nameKey: 'exchange_binance', realNameKey: 'exchange_binance_real' },
    { id: 'coinbase', nameKey: 'exchange_coinbase', realNameKey: 'exchange_coinbase_real' },
    { id: 'kucoin', nameKey: 'exchange_kucoin', realNameKey: 'exchange_kucoin_real' },
];

type TFunction = (key: string) => string;

export const getBotStrategies = (t: TFunction) => [
    {
        id: "dca",
        name: t('strategy_dca_name'),
        description: t('strategy_dca_description'),
        parameters: [
            { id: "amount", label: t('param_investment_amount'), type: "number", defaultValue: 100, tooltipKey: 'tooltip_param_investment_amount' },
            { id: "frequency", label: t('param_frequency'), type: "select", options: ["12 hours", "1 day", "3 days", "1 week"], defaultValue: "1 day", tooltipKey: 'tooltip_param_frequency' },
        ],
    },
    {
        id: "grid",
        name: t('strategy_grid_name'),
        description: t('strategy_grid_description'),
        parameters: [
            { id: "lowerPrice", label: t('param_lower_price'), type: "number", defaultValue: 58000, tooltipKey: 'tooltip_param_lower_price' },
            { id: "upperPrice", label: t('param_upper_price'), type: "number", defaultValue: 68000, tooltipKey: 'tooltip_param_upper_price' },
            { id: "grids", label: t('param_grid_number'), type: "number", defaultValue: 10, tooltipKey: 'tooltip_param_grid_number' },
        ],
    },
     {
        id: "momentum",
        name: t('strategy_momentum_name'),
        description: t('strategy_momentum_description'),
        parameters: [
             { id: "takeProfit", label: t('param_take_profit'), type: "number", defaultValue: 5, tooltipKey: 'tooltip_param_take_profit' },
             { id: "stopLoss", label: t('param_stop_loss'), type: "number", defaultValue: 2, tooltipKey: 'tooltip_param_stop_loss' },
        ],
    },
    {
        id: "trailing_stop",
        name: t('strategy_trailing_stop_name'),
        description: t('strategy_trailing_stop_description'),
        parameters: [
            { id: "trailPercentage", label: t('param_trail_percentage'), type: "number", defaultValue: 2, tooltipKey: 'tooltip_param_trail_percentage' },
            { id: "initialAmount", label: t('param_initial_amount'), type: "number", defaultValue: 100, tooltipKey: 'tooltip_param_initial_amount' },
        ],
    },
    {
        id: "scalping",
        name: t('strategy_scalping_name'),
        description: t('strategy_scalping_description'),
        parameters: [
            { id: "profitTarget", label: t('param_profit_target'), type: "number", defaultValue: 0.5, tooltipKey: 'tooltip_param_profit_target' },
            { id: "tradeAmount", label: t('param_trade_amount'), type: "number", defaultValue: 50, tooltipKey: 'tooltip_param_trade_amount' },
        ],
    },
    {
        id: "ma_crossover",
        name: t('strategy_ma_crossover_name'),
        description: t('strategy_ma_crossover_description'),
        parameters: [
            { id: "shortWindow", label: t('param_short_window'), type: "number", defaultValue: 9, tooltipKey: 'tooltip_param_short_window' },
            { id: "longWindow", label: t('param_long_window'), type: "number", defaultValue: 21, tooltipKey: 'tooltip_param_long_window' },
            { id: "tradeAmount", label: t('param_trade_amount'), type: "number", defaultValue: 100, tooltipKey: 'tooltip_param_trade_amount_crossover' },
        ],
    },
];